[package]
name = "buiy"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A comprehensive UI library for Bevy with web-quality accessibility."

[dependencies]
bevy.workspace = true
buiy_core = { path = "../buiy_core" }
buiy_widgets = { path = "../buiy_widgets" }
