//! E4 — the undo property test (editing-and-ime §§ 8, 12). For an arbitrary
//! script of edits, undoing every recorded unit restores the editor's initial
//! value and caret. Headless (cosmic shaping is CPU — no adapter). The script
//! is generated by proptest; each case builds a fresh editor, applies the
//! script, then undoes to exhaustion and asserts the round-trip.

use buiy_core::text::SharedFontSystem;
use buiy_core::text::edit::{EditCommand, EditContext, MemClipboard, TextEditState};
use cosmic_text::{Metrics, Motion};
use proptest::prelude::*;
use std::time::Duration;

/// One scripted edit. We restrict to the mutating + motion verbs the property
/// is about (insert/backspace/delete/enter/left/right) — clipboard/undo are
/// not part of the "undo-all is identity" invariant (Undo inside the script
/// would be testing the test).
#[derive(Debug, Clone)]
enum ScriptOp {
    Type(char),
    Backspace,
    Delete,
    Enter,
    Left,
    Right,
}

fn op_strategy() -> impl Strategy<Value = ScriptOp> {
    prop_oneof![
        // Bias toward typing so the buffer actually grows.
        4 => prop::char::range('a', 'z').prop_map(ScriptOp::Type),
        1 => Just(ScriptOp::Backspace),
        1 => Just(ScriptOp::Delete),
        1 => Just(ScriptOp::Enter),
        1 => Just(ScriptOp::Left),
        1 => Just(ScriptOp::Right),
    ]
}

fn apply_op(
    state: &mut TextEditState,
    fs: &mut cosmic_text::FontSystem,
    clip: &mut MemClipboard,
    op: &ScriptOp,
    now_ms: u64,
) {
    let mut ctx = EditContext {
        single_line: false,
        read_only: false,
        // Spread edits past the coalescing window so each op is its own unit
        // OR coalesces — both are valid; undo-all must restore regardless.
        now: Duration::from_millis(now_ms),
        clipboard: clip,
    };
    let cmd = match op {
        ScriptOp::Type(c) => EditCommand::Insert(c.to_string()),
        ScriptOp::Backspace => EditCommand::Backspace,
        ScriptOp::Delete => EditCommand::Delete,
        ScriptOp::Enter => EditCommand::Enter,
        ScriptOp::Left => EditCommand::Motion(Motion::Left, false),
        ScriptOp::Right => EditCommand::Motion(Motion::Right, false),
    };
    state.apply_tracked(fs, cmd, &mut ctx);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(128))]

    /// Undo-all restores the initial (empty) value and caret, for any script.
    #[test]
    fn undo_all_restores_the_initial_state(script in prop::collection::vec(op_strategy(), 0..40)) {
        let fonts = SharedFontSystem::new();
        let mut state = TextEditState::new(Metrics::new(16.0, 19.2));
        let mut fs = fonts.lock();
        let mut clip = MemClipboard::default();

        let initial_value = state.value();
        let initial_caret = state.caret();

        // Apply the script, time advancing ~50ms/op (some coalesce, some don't).
        for (i, op) in script.iter().enumerate() {
            apply_op(&mut state, &mut fs, &mut clip, op, (i as u64) * 50);
        }

        // Undo to exhaustion (each Undo pops one unit; advance time so the
        // Undo never coalesces with anything — it is non-mutating-of-stack).
        let mut guard = 0;
        while state.undo_depth() > 0 {
            let mut ctx = EditContext {
                single_line: false,
                read_only: false,
                now: Duration::from_millis(100_000 + guard * 50),
                clipboard: &mut clip,
            };
            state.apply_tracked(&mut fs, EditCommand::Undo, &mut ctx);
            guard += 1;
            prop_assert!(guard < 1000, "undo did not terminate");
        }

        prop_assert_eq!(state.value(), initial_value, "value restored");
        let c = state.caret();
        prop_assert_eq!(
            (c.line, c.index),
            (initial_caret.line, initial_caret.index),
            "caret restored"
        );
    }

    /// Redo-after-undo-all returns to the post-script value (the redo stack
    /// replays forward). Proves the `_after` restoration is sound.
    #[test]
    fn redo_after_full_undo_restores_the_final_value(
        script in prop::collection::vec(op_strategy(), 1..40)
    ) {
        let fonts = SharedFontSystem::new();
        let mut state = TextEditState::new(Metrics::new(16.0, 19.2));
        let mut fs = fonts.lock();
        let mut clip = MemClipboard::default();

        for (i, op) in script.iter().enumerate() {
            apply_op(&mut state, &mut fs, &mut clip, op, (i as u64) * 50);
        }
        let final_value = state.value();
        let units = state.undo_depth();

        let mut t = 100_000u64;
        for _ in 0..units {
            let mut ctx = EditContext { single_line: false, read_only: false, now: Duration::from_millis(t), clipboard: &mut clip };
            state.apply_tracked(&mut fs, EditCommand::Undo, &mut ctx);
            t += 50;
        }
        for _ in 0..units {
            let mut ctx = EditContext { single_line: false, read_only: false, now: Duration::from_millis(t), clipboard: &mut clip };
            state.apply_tracked(&mut fs, EditCommand::Redo, &mut ctx);
            t += 50;
        }
        prop_assert_eq!(state.value(), final_value, "redo-all returns to the final value");
    }
}
