//! Consolidated GPU integration-test binary for `buiy_verify`.
//!
//! Audit #9 (test-binary consolidation, plan T5.1): the former per-file
//! integration tests are grouped into two thin binaries to eliminate the
//! linear-in-binary-count link cost. This binary holds every test module that
//! emits at least one `#[ignore]` GPU test (real wgpu adapter / lavapipe); it
//! is exercised by the additive `--ignored` lane. The headless modules live in
//! the sibling `verify_headless` binary. Membership is decided by the runner's
//! ignored set, not a source grep: `reftest_cases_gpu`'s `#[ignore]` tests are
//! macro-generated by `reftest!`, so they are invisible to a plain grep.
//!
//! Each module is the unmodified former `tests/<name>.rs`, now included via an
//! explicit `#[path]` from `tests/verify_gpu/`. (An integration-test root file
//! resolves bare `mod` paths against `tests/` itself, not a subdirectory named
//! after the file, so the `#[path]` is required.) The modules reference the
//! library crate (`buiy_verify::support`, `buiy_verify::coverage`, …) via
//! external crate paths, which work unchanged inside a submodule.

#[path = "verify_gpu/coverage_forced_colors.rs"]
mod coverage_forced_colors;
#[path = "verify_gpu/coverage_golden.rs"]
mod coverage_golden;
#[path = "verify_gpu/determinism_build.rs"]
mod determinism_build;
#[path = "verify_gpu/determinism_capture.rs"]
mod determinism_capture;
#[path = "verify_gpu/goldens.rs"]
mod goldens;
#[path = "verify_gpu/reftest_cases_gpu.rs"]
mod reftest_cases_gpu;
#[path = "verify_gpu/reftest_engine_gpu.rs"]
mod reftest_engine_gpu;
#[path = "verify_gpu/reftest_macro_gpu.rs"]
mod reftest_macro_gpu;
#[path = "verify_gpu/sdf_cross_check_gpu.rs"]
mod sdf_cross_check_gpu;
