[package]
name = "buiy_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
taffy.workspace = true
tracing.workspace = true
bytemuck.workspace = true
accesskit.workspace = true
accesskit_winit.workspace = true
guillotiere = { workspace = true }
smallvec = { workspace = true }
bitflags = "2.11.1"

[dev-dependencies]
naga = "27"
